usb-FTDI_USB__-__Serial_Converter_FT94EVW4-if00-port0:
  side: "sample-config"
  num_joints: 7
  joint_signs: [1, 1, 1, 1, 1, -1, 1]
  gripper: true
  best_offsets: [6.283, 4.712, 3.142, 3.142, 3.142, 3.142, 4.712]
  gripper_range_rad: [2.77856, 3.50931]